-- Migration 037: MERGED INTO 036
-- The storage_path column addition and backfill that originally lived here
-- were merged into 036_stories_storage_and_cleanup.sql to fix a dependency
-- ordering bug: 036's cleanup function referenced storage_path before this
-- file had a chance to create it.
--
-- This file is intentionally left as a no-op placeholder so that any
-- migration runner tracking file numbers does not skip 037 entirely.
