import { useMemo, useRef } from "react";
import Mapbox from "@/lib/mapbox";
import type { SalonWithDistance } from "@/lib/discover";

// Exact colors sourced from tailwind.config.js and constants/theme.ts
const COLOR_WHITE = "#ffffff";
const COLOR_PRIMARY_500 = "#0a85f4"; // unselected text / cluster fill
const COLOR_MUTED = "#94a3b8"; // dark-400 — closed-salon text

// How much a closed salon's pin fades back so open salons pop forward.
const CLOSED_ICON_OPACITY = 0.5;
const CLOSED_TEXT_OPACITY = 0.65;

// Squircle bubble images (asymmetric Bubble.radiiSm corners), generated by
// scripts/generate-salon-markers.js. One per visual state; swapped via iconImage.
// The emerald "available now" dot is baked into the *-available variants so it
// takes part in symbol collision (a separate CircleLayer would orphan the dot
// when its pin is hidden by collision).
const PIN_IMAGES = {
	"salon-pin-default": require("@/assets/markers/salon-pin-default.png"),
	"salon-pin-available": require("@/assets/markers/salon-pin-available.png"),
	"salon-pin-selected": require("@/assets/markers/salon-pin-selected.png"),
	"salon-pin-selected-available": require("@/assets/markers/salon-pin-selected-available.png"),
	"salon-cluster": require("@/assets/markers/salon-cluster.png"),
};

// Image is 132px (44pt @3x); iconSize scales it down to ~display points.
const ICON_SIZE_DEFAULT = 0.34;
const ICON_SIZE_SELECTED = 0.4;

// Cluster settings. Below clusterMaxZoom nearby salons merge into a count bubble;
// above it every salon is its own (collision-managed) pin. Selecting a salon
// zooms to ≥14.5, so a selected pin is always in the unclustered regime.
const CLUSTER_RADIUS = 45;
const CLUSTER_MAX_ZOOM = 14;

// Score font. A SymbolLayer renders text from the Mapbox *style's* glyph source,
// NOT app-bundled fonts. "Euclid Circular A Bold" is uploaded on the
// `mihaicristian` account (verified: its glyphs return 200), but this only takes
// effect once the style's `glyphs` URL points at that account rather than the
// default `mapbox://fonts/mapbox/...` (which lacks the font and falls back to
// Arial). Fix in Mapbox Studio by using the font in the style — see notes to the
// dev. The trailing Arial entry guarantees pins still render if glyphs are missing.
const TEXT_FONT: string[] | null = ["Euclid Circular A Bold", "Arial Unicode MS Regular"];

interface Props {
	salons: SalonWithDistance[];
	selectedId: string | null;
	onSelect: (salon: SalonWithDistance) => void;
	/** Fired when a cluster is tapped, with the cluster centre and the zoom at
	 *  which it splits apart — the parent drives the camera there. */
	onClusterPress?: (coordinate: [number, number], expansionZoom: number) => void;
}

/**
 * SalonMarkersLayer — salon pins as a native Mapbox SymbolLayer, clustered.
 *
 * Why an image symbol (not MarkerView/PointAnnotation/CircleLayer): a MarkerView
 * laid out far outside the initial viewport never draws — confirmed it stays
 * invisible even when the salon is centred and selected. PointAnnotation
 * rasterizes its view unreliably; CircleLayer can only draw circles, not the
 * brand squircle. A SymbolLayer draws a bundled image natively, so every pin
 * renders at any position/zoom AND keeps the rounded-square bubble shape.
 *
 * Decluttering (two layers of defence):
 *  1. ShapeSource clustering collapses nearby salons into a count bubble.
 *  2. On the unclustered leaf pins, symbol collision is ON (allowOverlap/
 *     ignorePlacement false) so even spread-out pins never stack. `symbolSortKey`
 *     gives the selected pin top placement priority (then available, then higher
 *     rating), so the selected salon is never the one collision drops.
 */
export default function SalonMarkersLayer({
	salons,
	selectedId,
	onSelect,
	onClusterPress,
}: Props) {
	const shapeRef = useRef<Mapbox.ShapeSource>(null);

	const shape = useMemo(() => {
		const features = salons
			.filter((s) => s.latitude != null && s.longitude != null)
			.map((s) => {
				const hasRating =
					s.rating_avg != null &&
					s.reviews_count != null &&
					s.reviews_count > 0;
				const selected = s.id === selectedId;
				const available = !!s.is_available_now;
				const open = !!s.is_open_now;
				// Lower sortKey = higher collision-placement priority. Selected always
				// wins; then available; then higher-rated; closed salons are pushed
				// down so an open salon wins when the two overlap.
				const sortKey = selected
					? 0
					: 100 -
						(hasRating ? (s.rating_avg as number) * 10 : 0) -
						(available ? 5 : 0) +
						(open ? 0 : 8);
				return {
					type: "Feature" as const,
					id: s.id,
					geometry: {
						type: "Point" as const,
						coordinates: [s.longitude as number, s.latitude as number],
					},
					properties: {
						salonId: s.id,
						label: hasRating ? (s.rating_avg as number).toFixed(1) : "Nou",
						available,
						selected,
						open,
						sortKey,
					},
				};
			});
		return { type: "FeatureCollection" as const, features };
	}, [salons, selectedId]);

	const handlePress = async (e: any) => {
		const feature = e?.features?.[0];
		if (!feature) return;
		const props = feature.properties ?? {};

		// Cluster tap → expand it: fly to the zoom at which it splits apart.
		if (props.cluster || props.point_count != null) {
			try {
				const zoom = await shapeRef.current?.getClusterExpansionZoom(feature);
				const coords = feature.geometry?.coordinates;
				if (coords && zoom != null) {
					onClusterPress?.([coords[0], coords[1]], zoom);
				}
			} catch {
				// getClusterExpansionZoom can reject if the cluster tree isn't ready;
				// a no-op is fine — the user can tap again or pinch to zoom.
			}
			return;
		}

		const salon = salons.find((s) => s.id === props.salonId);
		if (salon) onSelect(salon);
	};

	return (
		<>
			<Mapbox.Images images={PIN_IMAGES} />
			<Mapbox.ShapeSource
				id='salons-src'
				ref={shapeRef}
				shape={shape}
				cluster
				clusterRadius={CLUSTER_RADIUS}
				clusterMaxZoomLevel={CLUSTER_MAX_ZOOM}
				onPress={handlePress}>
				{/* ── Cluster bubble: brand squircle + white count ── */}
				<Mapbox.SymbolLayer
					id='salon-clusters'
					filter={["has", "point_count"]}
					style={{
						iconImage: "salon-cluster",
						// Grow the bubble as the cluster gets larger (image is 132px;
						// these keep it downscaled, so it stays crisp).
						iconSize: ["step", ["get", "point_count"], 0.4, 10, 0.48, 25, 0.58],
						iconAllowOverlap: true,
						iconIgnorePlacement: true,
						textField: ["get", "point_count_abbreviated"],
						textSize: ["step", ["get", "point_count"], 14, 10, 15, 25, 16],
						textColor: COLOR_WHITE,
						...(TEXT_FONT ? { textFont: TEXT_FONT } : {}),
						textAllowOverlap: true,
						textIgnorePlacement: true,
					}}
				/>

				{/* ── Individual salon pins (unclustered leaves), collision-managed ── */}
				<Mapbox.SymbolLayer
					id='salons-pin'
					filter={["!", ["has", "point_count"]]}
					style={{
						iconImage: [
							"case",
							["all", ["get", "selected"], ["get", "available"]],
							"salon-pin-selected-available",
							["get", "selected"],
							"salon-pin-selected",
							["get", "available"],
							"salon-pin-available",
							"salon-pin-default",
						],
						iconSize: [
							"case",
							["get", "selected"],
							ICON_SIZE_SELECTED,
							ICON_SIZE_DEFAULT,
						],
						// Closed salons fade back so open ones stand out (a selected pin
						// stays fully opaque even if closed, so the tapped salon is clear).
						iconOpacity: [
							"case",
							["any", ["get", "selected"], ["get", "open"]],
							1,
							CLOSED_ICON_OPACITY,
						],
						// Collision ON — the selected pin (sortKey 0) is placed first and
						// always survives; overlapping lower-priority pins are dropped.
						iconAllowOverlap: false,
						iconIgnorePlacement: false,
						symbolSortKey: ["get", "sortKey"],
						textField: ["get", "label"],
						textSize: 13,
						...(TEXT_FONT ? { textFont: TEXT_FONT } : {}),
						textColor: [
							"case",
							["get", "selected"],
							COLOR_WHITE,
							["get", "open"],
							COLOR_PRIMARY_500,
							COLOR_MUTED,
						],
						textOpacity: [
							"case",
							["any", ["get", "selected"], ["get", "open"]],
							1,
							CLOSED_TEXT_OPACITY,
						],
						// The label rides with its icon; let it drop before the icon does
						// so a pin never vanishes just because its score can't fit.
						textAllowOverlap: false,
						textIgnorePlacement: false,
						textOptional: true,
					}}
				/>
			</Mapbox.ShapeSource>
		</>
	);
}
