import { useMemo } from "react";
import Mapbox from "@/lib/mapbox";
import type { SalonWithDistance } from "@/lib/discover";

// Exact colors sourced from tailwind.config.js and constants/theme.ts
const COLOR_WHITE = "#ffffff";
const COLOR_PRIMARY_500 = "#0a85f4"; // unselected text
const COLOR_AVAILABLE = "#10b981"; // emerald-500 — availability dot

// Squircle bubble images (asymmetric Bubble.radiiSm corners), generated by
// scripts/generate-salon-markers.js. One per visual state; swapped via iconImage.
const PIN_IMAGES = {
	"salon-pin-default": require("@/assets/markers/salon-pin-default.png"),
	"salon-pin-available": require("@/assets/markers/salon-pin-available.png"),
	"salon-pin-selected": require("@/assets/markers/salon-pin-selected.png"),
};

// Image is 132px (44pt @3x); iconSize scales it down to ~display points.
const ICON_SIZE_DEFAULT = 0.34;
const ICON_SIZE_SELECTED = 0.4;

// Score font. A SymbolLayer renders text from the Mapbox *style's* glyph source,
// NOT app-bundled fonts. "Euclid Circular A Bold" is uploaded on the
// `mihaicristian` account (verified: its glyphs return 200), but this only takes
// effect once the style's `glyphs` URL points at that account rather than the
// default `mapbox://fonts/mapbox/...` (which lacks the font and falls back to
// Arial). Fix in Mapbox Studio by using the font in the style — see notes to the
// dev. The trailing Arial entry guarantees pins still render if glyphs are missing.
const TEXT_FONT: string[] | null = ["Euclid Circular A Bold", "Arial Unicode MS Regular"];

interface Props {
	salons: SalonWithDistance[];
	selectedId: string | null;
	onSelect: (salon: SalonWithDistance) => void;
}

/**
 * SalonMarkersLayer — salon pins as a native Mapbox SymbolLayer.
 *
 * Why an image symbol (not MarkerView/PointAnnotation/CircleLayer): a MarkerView
 * laid out far outside the initial viewport never draws — confirmed it stays
 * invisible even when the salon is centred and selected. PointAnnotation
 * rasterizes its view unreliably; CircleLayer can only draw circles, not the
 * brand squircle. A SymbolLayer draws a bundled image natively, so every pin
 * renders at any position/zoom AND keeps the rounded-square bubble shape. The
 * rating/"Nou" label is the symbol's text; the availability dot is a small
 * offset CircleLayer.
 */
export default function SalonMarkersLayer({
	salons,
	selectedId,
	onSelect,
}: Props) {
	const shape = useMemo(() => {
		const features = salons
			.filter((s) => s.latitude != null && s.longitude != null)
			.map((s) => {
				const hasRating =
					s.rating_avg != null &&
					s.reviews_count != null &&
					s.reviews_count > 0;
				return {
					type: "Feature" as const,
					id: s.id,
					geometry: {
						type: "Point" as const,
						coordinates: [s.longitude as number, s.latitude as number],
					},
					properties: {
						salonId: s.id,
						label: hasRating ? (s.rating_avg as number).toFixed(1) : "Nou",
						available: !!s.is_available_now,
						selected: s.id === selectedId,
					},
				};
			});
		return { type: "FeatureCollection" as const, features };
	}, [salons, selectedId]);

	const handlePress = (e: any) => {
		const id = e?.features?.[0]?.properties?.salonId;
		if (!id) return;
		const salon = salons.find((s) => s.id === id);
		if (salon) onSelect(salon);
	};

	return (
		<>
			<Mapbox.Images images={PIN_IMAGES} />
			<Mapbox.ShapeSource
				id='salons-src'
				shape={shape}
				onPress={handlePress}>
				{/* Squircle bubble + rating label. iconImage swaps the tint by state. */}
				<Mapbox.SymbolLayer
					id='salons-pin'
					style={{
						iconImage: [
							"case",
							["get", "selected"],
							"salon-pin-selected",
							["get", "available"],
							"salon-pin-available",
							"salon-pin-default",
						],
						iconSize: [
							"case",
							["get", "selected"],
							ICON_SIZE_SELECTED,
							ICON_SIZE_DEFAULT,
						],
						iconAllowOverlap: true,
						iconIgnorePlacement: true,
						textField: ["get", "label"],
						textSize: 13,
						...(TEXT_FONT ? { textFont: TEXT_FONT } : {}),
						textColor: [
							"case",
							["get", "selected"],
							COLOR_WHITE,
							COLOR_PRIMARY_500,
						],
						textAllowOverlap: true,
						textIgnorePlacement: true,
					}}
				/>
				{/* Availability dot — only for bookable-now salons, pinned to the
            bubble's top-right via a constant screen-space offset. */}
				<Mapbox.CircleLayer
					id='salons-dot'
					filter={["==", ["get", "available"], true]}
					style={{
						circleRadius: 5,
						circleColor: COLOR_AVAILABLE,
						circleStrokeWidth: 2,
						circleStrokeColor: COLOR_WHITE,
						circleTranslate: [13, -13],
						circleTranslateAnchor: "viewport",
					}}
				/>
			</Mapbox.ShapeSource>
		</>
	);
}
